name: ppv_components
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  go_router: ^16.2.0
  cupertino_icons: ^1.0.8
  flutter_date_pickers: ^0.4.3
  provider: ^6.1.5+1
  data_table_2: ^2.5.8
  image_picker: ^1.2.0
  pdf: ^3.11.3
  typed_data: ^1.4.0
  fluent_ui: ^4.12.0
  flutter_value_notifier: ^1.6.0
  printing: ^5.14.2
  http: ^1.5.0               #for http request
  grpc: ^4.1.0             #for grpc request
  protobuf: ^4.2.0
  flutter_dotenv: ^6.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/




